### ISSUE TITLE
Load Modeling tracking issue

### ISSUE THREAD

**Issue by jd-lara** [NREL-SIIP/PowerSystems.jl#847]
### Discussed in https://github.com/NREL-SIIP/PowerSystems.jl/discussions/846

<div type='discussions-op-text'>

<sup>Originally posted by **jd-lara** January 17, 2022</sup>
We are opening this discussion for the re-design of load modeling in PowerSystems.jl to include: 

- [x] Dynamic Modeling of ZIP loads
- [ ]  Price Sensitivity of loads. 
- [x] Refactor the use of ENUMS for types to dispatch on AC load behavior.

**Comment by AlOussama** [comment]
What is the state of the dynamic load modeling? are they available in the master branch?

**Comment by jd-lara** [comment]
> What is the state of the dynamic load modeling? are they available in the master branch?

This is already available, just not documented. @rodrigomha can you provide an example?

**Comment by rodrigomha** [comment]
We have Load Modeling for Zip Load and Exponential Loads, as commonly represented in time-domain phasor simulations: https://github.com/NREL-SIIP/PowerSimulationsDynamics.jl/blob/master/src/models/load_models.jl

For dynamic load models with differential equations we have 5th and 3rd order induction machines:
https://nrel-siip.github.io/PowerSimulationsDynamics.jl/stable/component_models/loads/
and something that is not documented is the active load model:
https://github.com/NREL-SIIP/PowerSimulationsDynamics.jl/blob/204292b749758b1607df3126c3672557e1d9e9d1/src/models/device.jl#L918

All of these models are in master branch in PowerSystems and PowerSimulationsDynamics

There is some discussion of including RL dynamic load with current dynamics using differential equations, but is not something that we plan to do in the short term.

**Comment by AlOussama** [comment]
Thanks for the detailed Information. 
Concerning dynamic load models, for example "3rd Order induction machines": how to add it to already existing static constant load? Is it analog to the code used for adding the dynamic generator model to the static one? Or is it directly added to the bus as new load model. Do you have an example?
